typography_spectrum: 0.39953755610622466
color:
  brandStrength: 0.834774186834693
  lightness: 0.8791117705404758
  saturation: 0.48585012392140925
  rhythmicContrast: 0.9342356536071748
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.7207751022651792
name: Beta Computers
navigation:
  - name: buy lovable mac at a Fraction of new pricing
    url: www.BetaMacs.com
    type: external
title: The only Guarantee in life is that life will change
